# Generated by Django 4.2.17 on 2025-01-16 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caravan',
            old_name='name',
            new_name='title',
        ),
    ]
