# Generated by Django 4.2.17 on 2025-01-21 15:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_caravan_berth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
