# Generated by Django 4.2.17 on 2025-01-22 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0007_alter_availability_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to=settings.AUTH_USER_MODEL),
        ),
    ]
