# Generated by Django 4.2.17 on 2025-01-22 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_amenity_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caravan',
            name='available_dates',
        ),
    ]
