# Generated by Django 4.2.17 on 2025-01-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_remove_caravan_available_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caravan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
