# Generated by Django 4.2.17 on 2025-01-23 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_alter_caravan_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='caravan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='listings.caravan'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='caravan',
            name='berth',
            field=models.CharField(choices=[('small', 'Two-berth'), ('medium', 'Four-berth'), ('large', 'Six-berth')], max_length=10),
        ),
        migrations.AlterField(
            model_name='caravan',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/images/'),
        ),
    ]
