# Generated by Django 4.2.17 on 2025-01-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_alter_availability_caravan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caravan',
            name='image',
            field=models.ImageField(blank=True, default='static/images/default.jpg', upload_to='static/images/'),
        ),
    ]
