# Generated by Django 4.2.17 on 2025-01-27 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_alter_caravan_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caravan',
            name='image',
        ),
        migrations.CreateModel(
            name='CaravanImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images/')),
                ('caravan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.caravan')),
            ],
        ),
    ]
