# Generated by Django 4.2.17 on 2025-02-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_alter_booking_caravan_alter_booking_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caravan',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
