# Generated by Django 4.2.17 on 2025-02-06 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_caravan_is_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caravan',
            old_name='is_favorite',
            new_name='is_favourite',
        ),
    ]
