# Generated by Django 4.2.17 on 2025-02-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
