# Generated by Django 4.2.17 on 2025-02-14 10:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0020_remove_review_reply_review_updated_at_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caravan',
            name='is_favourite',
        ),
        migrations.AddField(
            model_name='caravan',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='favourite_caravans', to=settings.AUTH_USER_MODEL),
        ),
    ]
