# Generated by Django 4.2.17 on 2025-03-01 19:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_alter_booking_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caravanimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
