# Generated by Django 4.2.17 on 2025-03-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0024_alter_caravanimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caravan',
            name='location',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='caravan',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
