# Generated by Django 4.2.17 on 2025-02-20 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('review', 'Review'), ('reply_to_review', 'Reply to Review'), ('booking_request', 'Booking Request'), ('booking_confirmation', 'Booking Confirmation'), ('contact_form_message', 'Contact Form Message')], default='review', max_length=20),
        ),
    ]
