# Generated by Django 4.2.17 on 2025-02-21 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_caravan_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_settings', '0007_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='listings.booking'),
        ),
        migrations.AddField(
            model_name='notification',
            name='caravan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='listings.caravan'),
        ),
        migrations.AddField(
            model_name='notification',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('review', 'Review'), ('reply_to_review', 'Reply to Review'), ('booking_request', 'Booking Request'), ('booking_accepted', 'Booking Accepted'), ('booking_declined', 'Booking Declined'), ('booking_modified_request', 'Booking ModifiCATION Request'), ('contact_form_message', 'Contact Form Message')], default='booking_request', max_length=50),
        ),
    ]
