# Generated by Django 4.2.17 on 2025-02-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0008_notification_booking_notification_caravan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('review', 'Review'), ('reply_to_review', 'Reply to Review'), ('booking_request', 'Booking Request'), ('booking_accepted', 'Booking Accepted'), ('booking_declined', 'Booking Declined'), ('booking_modified_request', 'Booking Modification Request'), ('contact_form_message', 'Contact Form Message')], max_length=50),
        ),
    ]
